### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by inphosec** [InfoSecInnovations/concierge#27]
The Concierge install seemed to go ok. However, when I try to launch it, I get a Module Not Found error.

└─$ python3 launch.py                            
Traceback (most recent call last):
  File "/home/kali/concierge/concierge_installer/launcher.py", line 2, in <module>
    from script_builder.util import get_venv_executable
ModuleNotFoundError: No module named 'script_builder'

I installed this on Kali Linux (version 2024.1).

**Comment by wretiii** [comment]
Rather than running launch.py, try `streamlit run Concierge.py`

**Comment by inphosec** [comment]
I get "command not found" running steamlit. Is it something I may need to install as well?

┌──(kali㉿kali)-[~/concierge]
└─$ streamlit run Concierge.py
streamlit: command not found

**Comment by wretiii** [comment]
I recommend first ensuring that install.py completes successfully, then running through the documented manual processes if it doesn't. I had to do a mostly manual setup and launch for it to get up and running, and also had to update my CUDA drivers before everything worked as expected.

**Comment by inphosec** [comment]
Thank you. I'll try your suggestions.

**Comment by JGifford** [comment]
> I get "command not found" running steamlit. Is it something I may need to install as well?

Try entering the python virtual environment before running the streamlit command.
The "[Usage:manual](https://github.com/InfoSecInnovations/concierge?tab=readme-ov-file#usage-manual)" section suggests entering the "python virtual environment" first:
`source ./bin/activate`
and then start the web UI:
`streamlit run Concierge.py`

**Comment by sebovzeoueb** [comment]
Hello, we're aware of the missing `script_builder` module issue, a fix has been implemented in 0.2.0 which is coming soon.

**Comment by rexroder** [comment]
I have it running on Arch I had to do the manual install:
Setup: manual

If install.py did not work, follow these steps to setup your system.

python -m venv . create a python virtual environment in the current directory.

Linux: source ./bin/activate / Windows PowerShell: .\Scripts\Activate.ps1 enter into the virtual environment.

pip install -r requirements.txt install all dependencies.

copy .env.example into a file named .env and set the folder on your computer that will contain the concierge data.

docker compose up -d will load the docker dependencies.

docker compose -f docker-compose-gpu.yml up -d will load the docker dependencies and use the GPU.

**Comment by sebovzeoueb** [comment]
0.3.0 should fix current installation issues.
