### ISSUE TITLE
install.py: docker: unkown shorthand flag 'd' in -d

### ISSUE THREAD

**Issue by markjx** [InfoSecInnovations/concierge#28]
I'm having installation trouble on Ubuntu 23.10 & 24.04. I've done multiple tests with both, the results are very consistent.

I first run:
`sudo apt install -y docker.io docker-compose python3.11-venv`

Then I do the `python3 ./install.py` and answer all the questions.
It downloads and installs lots of stuff, then I get an error message:
`unknown shorthand flag: 'd' in -d
See 'docker --help'.`
Followed by the docker help, followed by
`Error response from daemon: No such container: ollama`

Not sure what to try next.

**Comment by sebovzeoueb** [comment]
From what I can see, the Ubuntu install process for Docker has more steps than that, have you tried this? https://docs.docker.com/engine/install/ubuntu/ 

Docker Desktop exists on Linux these days too if you want to have the GUI!

**Comment by markjx** [comment]
Great! That seems to have done it 😸 

I created a script to install on Ubuntu:
[concierge-install-ubuntu.txt](https://github.com/InfoSecInnovations/concierge/files/15275636/concierge-install-ubuntu.txt)
