### ISSUE TITLE
How to confirm concierge is using GPU?

### ISSUE THREAD

**Issue by shipley-c** [InfoSecInnovations/concierge#30]
I just got a new nVidia 4080 Super RTX with 16GB RAM.  I'm installing into Windows 10 Home, running WSL 2.  nvidia-smi from Ubuntu on WSL shows that it has access to the card and is running CUDA 12.5:
![image](https://github.com/InfoSecInnovations/concierge/assets/157814625/0ff0cc91-3be5-4fe5-8f40-c5dfef09a564)

I ingested 4 simple web pages of data into a new collection.  These are small 1-2 page KB articles.  It's taking a lot of minutes to ask simple queries of the collection.  How can I verify this is using GPU vs CPU?  I definitely selected GPU in when I ran install.py  I don't think this is using GPU due to the speed at which I'm getting results.

**Comment by sebovzeoueb** [comment]
Is it taking a lot of minutes all the time, or only the first time and after 5 minutes of idle time and then subsequent queries are fast?

**Comment by shipley-c** [comment]
Thank you for your help.

I added more URLs for ingestion yesterday, so total ingested 20 URLs of those 1-2 page KB articles.
I started up docker and ran launch.py this morning.  I ran a task:question prompt against the collection (no persona, no enhancers), it took ~5 minutes
I ran the same task:question again, it took less than a minute.

What are the elements that are taking time to load/process?  Is there a way we can prime the system before asking our first question?

I'm having difficulty finding the log files I'd setup during install.py - I checked the install.py script and couldn't find any reference to asking me where the log files would be or what their default would be.  I think getting a look at the log files will start to help me understand what's going on.  The console is okay, but it doesn't contain timestamps and scrolling through that vs using a text editor is a bit of a burden.  Any clue where default log files would be?  A search of "logs" on my entire C: drive didn't turn up any concierge related folders outside of .git

**Comment by shipley-c** [comment]
I can confirm that the only thing using my GPU is chrome browser at about 4% during a query according to my system os, and vmmem is using between 70-95% CPU  Perhaps I don't understand what "GPU enhanced" means for the processes - but I'd assume the LLM would be loaded into and utilizing the GPUs

**Comment by shipley-c** [comment]
nVidia released a new driver for the RTX 4080 SUPER yesterday, top of the general bug fixes:
- CUDA 12.5 does not work with CUDA enabled Docker images [4668302]

I just updated, I think I'm good now.  I just got in a real lucky hole! lol

**Comment by sebovzeoueb** [comment]
Great, thanks for reporting back on this, it'll help us if other people have this issue! 

BTW, we're enabling this in the upcoming release, but if you want to keep Ollama "warmed up" you can set ```     environment:
      - OLLAMA_KEEP_ALIVE=-1``` under the `ollama` service in the compose file. You still get the initial startup, but after that it the responses will stay snappy so long as the container is running.

**Comment by shipley-c** [comment]
I have a little more data here.  ollama is still not using CUDA 12.5, but I think that might be because I just ran the install.py from the main branch?  a little investigation shows it contains cuda 11 but not 12.5.  What's the best approach here?  CAn I just grab a new ollama container?  will I need to string it to the other containers somehow?  forgive me, I know a lot about a little, and a little about a lot - this is my first real entry into OSS AI systems outside of running a few tensors, tokenizers, and llms from within a quick python script.

**Comment by shipley-c** [comment]
OK, I had to do a couple things here.  First, I had to revert to CUDA 12.4
https://stackoverflow.com/questions/78558553/docker-container-with-cuda-does-not-see-my-gpu-wsl2-ubuntu-win10-nvcc

I changed to the development branch, ran install_dev.py
Then, I had to tell ollama to use cuda 12.4 version in the docker-compose-ollama.yml file by adding an environment variable:
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      **_- OLLAMA_LLM_LIBRARY=cuda_v12.4_**
 
Now I have evidence om the ollama:latest docker container logs that it has detected CUDA, a single gpu, and that it has offloaded tasks from CPU to GPU.
