### ISSUE TITLE
Can we add a wiki to the repository?

### ISSUE THREAD

**Issue by shipley-c** [InfoSecInnovations/concierge#32]
The README.MD is nice and so is the issues list, but a wiki with some how-to documentation (like when I finalize my CUDA 12.5 journey, which may require me to reinstall down to 12.4) would be a really great thing for me to start contributing to.

**Comment by shipley-c** [comment]
Just a follow-up, anyone?

**Comment by sebovzeoueb** [comment]
Good idea! I've made it public for the moment, please feel free to contribute, we'll see if in the future we need to restrict editing or not.
