### ISSUE TITLE
Last prompt in `install.py` doesn't default to "Y" as indicated

### ISSUE THREAD

**Issue by flakpaket** [InfoSecInnovations/concierge#7]
After using `Enter` for the defaults all the way through the install script, the install exits with the following message:

```
Ready to apply settings and start downloading? [Y/n]: 
Install cancelled. No changes were made. Have a nice day! :-)
```
Adding ` or "Y"` to the end of line 95 of `install.py` should fix it.
https://github.com/InfoSecInnovations/concierge/blob/3c4a299e9cdf24dfd4be0d118f82080666d4d764/install.py#L95

**Comment by besimorhino** [comment]
While hitting `Enter` will get you to the last question, we do want folks to have to take a positive Y to do the install. I.e., this is I think a good thing?

Would you be more open to the "must hit `Y`" if we worded that final prompt a bit differently?

**Comment by flakpaket** [comment]
As a user, it cancelled without error, and I had to read the code to figure out why.
 
The `[Y/n]` at the end follows a common convention that the caps option would be the default, which I think is what had me confused. 

So, either make them both should be capital, or add language as you suggested. 

Following flows that folks are more likely used to, you could do something similar to SSH when contacting a new system.

**Comment by flakpaket** [comment]
Note that someone that enters `y` instead of `Y` to that prompt will cancel their install, as well, since line 97 doesn't use `.upper()`. It will jump straight to line 123. They'd probably be more confused than I was.  
https://github.com/InfoSecInnovations/concierge/blob/3c4a299e9cdf24dfd4be0d118f82080666d4d764/install.py#L97-L125

**Comment by besimorhino** [comment]
Excellent feedback. Thanks so much. Will test with the "ssh" style option first.

**Comment by flakpaket** [comment]
I think that's clearer. (Personally, I don't see the need to default to "no" for the final opt-in, but it's at least clear what's happing now.)

**Comment by besimorhino** [comment]
OK sounds like we got what you were after. Please re-open if you think this needs further work.

Cheers!
