### ISSUE TITLE
Creating a collection name with a space produces an error

### ISSUE THREAD

**Issue by flakpaket** [InfoSecInnovations/concierge#8]
<img width="761" alt="image" src="https://github.com/InfoSecInnovations/concierge/assets/11314975/f91479e3-6a3f-4a6f-8eea-dec447118e2d">

**Comment by besimorhino** [comment]
Summary:
fixed. Added a hint below text input area.

Details:
See picture.
![image](https://github.com/InfoSecInnovations/concierge/assets/2036208/69fb6df4-3920-40d6-a910-4f2234b54cc3)

Please review and if this meets your expectations, please close this ticket. If not, please let us know what we need to do to make this a better experience for you.

Thanks again.

**Comment by besimorhino** [comment]
closing as complete.
